const pendus: string[] = []

pendus[10] = ` ______
|/     |
|      O 
|     \\_/
|      |
|     / \\
|_______`

pendus[9] = ` ______
|/     |
|      O 
|     \\_/
|      |
|     / 
|_______`

pendus[8] = ` ______
|/     |
|      O 
|     \\_/
|      |
|      
|_______`

pendus[7] = ` ______
|/     |
|      O 
|     \\_/
|      
|      
|_______`

pendus[6] = ` ______
|/     |
|      O 
|     \\_
|      
|      
|_______`

pendus[5] = ` ______
|/     |
|      O 
|      
|      
|      
|_______`

pendus[4] = ` ______
|/     |
|      
|      
|      
|      
|_______`

pendus[3] = ` ______
|/     
|      
|      
|      
|      
|_______`

pendus[2] = `|/     
|      
|      
|      
|      
|_______`

pendus[1] = `|
|
|
|
|
|_______`

pendus[0] = `   
      
      
      
      
________`

const surprise: string = decodeURI(
  atob(
    'JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJUIwJUUyJUExJUJGJUUyJUEwJThCJUUyJUEwJTgxJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTg4JUUyJUEwJTg5JUUyJUEwJTk5JUUyJUEwJUJCJUUyJUEzJUI3JUUyJUEzJTg0JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJTBBJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJTgwJUUyJUEzJUJGJUUyJUEwJTg3JUUyJUEwJTgwJUUyJUEyJTgwJUUyJUEzJUI0JUUyJUEzJUI2JUUyJUExJUJFJUUyJUEwJUJGJUUyJUEwJUJGJUUyJUEwJUJGJUUyJUEyJUJGJUUyJUEzJUJGJUUyJUEzJUE2JUUyJUExJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJTBBJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEzJTgwJUUyJUEzJTgwJUUyJUEzJUI4JUUyJUExJUJGJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJUI4JUUyJUEzJUJGJUUyJUEzJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTk5JUUyJUEzJUI3JUUyJUExJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJTBBJUUyJUEwJTgwJUUyJUEzJUJFJUUyJUExJTlGJUUyJUEwJTlCJUUyJUEzJUJGJUUyJUExJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJUI4JUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUI3JUUyJUEzJUE0JUUyJUEzJUE0JUUyJUEzJUE0JUUyJUEzJUE0JUUyJUEzJUI2JUUyJUEzJUI2JUUyJUEzJUJGJUUyJUEwJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEzJTgwJUUyJUEwJTgwJUUyJUEwJTgwJTBBJUUyJUEyJTgwJUUyJUEzJUJGJUUyJUEwJTgwJUUyJUEyJTgwJUUyJUEzJUJGJUUyJUExJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJUJCJUUyJUEyJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEwJUJGJUUyJUEzJUJGJUUyJUExJThGJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJUI0JUUyJUEzJUI2JUUyJUEzJUI2JUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJTg2JTBBJUUyJUEyJUI4JUUyJUEzJUJGJUUyJUEwJTgwJUUyJUEyJUI4JUUyJUEzJUJGJUUyJUExJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTg4JUUyJUEwJTg5JUUyJUEwJTgxJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEzJUJGJUUyJUExJTg3JUUyJUEzJTgwJUUyJUEzJUEwJUUyJUEzJUI0JUUyJUEzJUJFJUUyJUEzJUFFJUUyJUEzJTlEJUUyJUEwJUJGJUUyJUEwJUJGJUUyJUEwJUJGJUUyJUEzJUJCJUUyJUExJTlGJTBBJUUyJUEyJUI4JUUyJUEzJUJGJUUyJUEwJTgwJUUyJUEwJTk4JUUyJUEzJUJGJUUyJUExJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEzJUEwJUUyJUEzJUI2JUUyJUEzJUJFJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUExJUJGJUUyJUEwJTgxJUUyJUEwJTg5JUUyJUEwJTgwJTBBJUUyJUEwJUI4JUUyJUEzJUJGJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEzJUJGJUUyJUExJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEzJUEwJUUyJUEzJUJFJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUExJUJGJUUyJUEwJTlGJUUyJUEwJTg5JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJTBBJUUyJUEwJTgwJUUyJUEwJUJCJUUyJUEzJUI3JUUyJUEzJUI2JUUyJUEzJUJGJUUyJUEzJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJUEwJUUyJUEzJUJDJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJTlCJUUyJUEzJTlCJUUyJUEzJUJCJUUyJUEwJTg5JUUyJUEwJTgxJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJTBBJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJUI4JUUyJUEzJUJGJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJUI4JUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUExJTg3JUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJTBBJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEwJTgwJUUyJUEyJUI4JUUyJUEzJUJGJUUyJUEzJTgwJUUyJUEzJTgwJUUyJUEzJTgwJUUyJUEzJUJDJUUyJUExJUJGJUUyJUEyJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUExJUJGJUUyJUEzJUJGJUUyJUEzJUJGJUUyJUExJUJG'
  )
)

export { pendus, surprise }
